# Generated by Django 6.0.2 on 2026-03-02 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
