# Generated by Django 6.0.2 on 2026-03-04 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id',
                 models.CharField(db_index=True, help_text='Stripe PaymentIntent ID (e.g., pi_1234567890)',
                                  max_length=255, unique=True)),
                ('status', models.CharField(
                    choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'),
                             ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True,
                    default='pending', help_text='Current payment status', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount in the specified currency',
                                               max_digits=20)),
                ('currency',
                 models.CharField(default='usd', help_text="Three-letter ISO currency code (e.g., 'usd', 'eur')",
                                  max_length=3)),
                ('failure_message',
                 models.TextField(blank=True, help_text='Error message if payment failed', null=True)),
                ('idempotency_key',
                 models.CharField(blank=True, help_text='Unique key to ensure payment is only processed once',
                                  max_length=255, null=True, unique=True)),
                ('client_secret',
                 models.CharField(blank=True, help_text='Stripe client secret for frontend payment confirmation',
                                  max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the payment was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the payment was last updated')),
                ('order', models.OneToOneField(help_text='The order this payment is associated with',
                                               on_delete=django.db.models.deletion.CASCADE, related_name='payment',
                                               to='orders.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
                            models.Index(fields=['stripe_payment_intent_id'], name='payments_pa_stripe__6fe52c_idx')],
            },
        ),
    ]
